# Generated by Django 5.1.3 on 2024-11-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_version_documentchunk_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01T00:00:00'),
            preserve_default=False,
        ),
    ]
